import Config

# This manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :conecerto_scoreboard, Conecerto.ScoreboardWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info
