name: Build release
on:
  workflow_dispatch:
  release:
    types: [published]

# Make sure the GITHUB_TOKEN has permission to upload to our releases
permissions:
  contents: write

jobs:
  mix-release:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '27'
          elixir-version: '1.18'
      - name: Get dependencies
        run: mix deps.get
      - name: Overwrite buggy inotifywait
        run: cp .\misc\inotifywait.exe .\deps\file_system\priv\
      - name: Build
        run: |
          mix assets.deploy
          mix release
          mix phx.digest.clean --all
        env:
          MIX_ENV: prod
      - name: Upload
        run: gh release upload ${{github.event.release.tag_name}} (Get-Item .\_build\prod\*.zip)
        env:
          GH_TOKEN: ${{ github.token }}
