name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mix-test:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '27'
          elixir-version: '1.18'
      - name: Get dependencies
        run: mix deps.get
      - name: Overwrite buggy inotifywait
        run: cp .\misc\inotifywait.exe .\deps\file_system\priv\
      - name: Test
        run: mix test
