name: Test
on:
  push:

jobs:
  mix-test:
    name: mix test
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '27'
          elixir-version: '1.17'
      - name: Build
        shell: cmd
        run: mix deps.get
      - name: Test
        shell: cmd
        run: mix test
